services:
  seguimiento_postoperatorio:
    image: ymoras/seguimiento_postoperatorio_ms:latest
    container_name: seguimiento_postoperatorio
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb+srv://root:AAJJY52024-2@cluster0.ocbp0.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MONGO_DATABASE=postcare_seguimiento_postoperatorio_db
      - SERVER_PORT=8081
      - SPRING_APPLICATION_NAME=seguimiento_postoperatorio_ms
    networks:
      - backend

  registro_usuario:
    image: amoralesco/postcare_registro_usuario_ms:v4
    container_name: registro_usuario
    ports:
      - "8000:8000" 
    networks:
      - backend

  triage:
    image: amoralesco/postcare_triage_ms:v1
    container_name: triage
    ports:
      - "8003:8003" 
    networks:
      - backend
  educativo_ms:
    image: postcare_educativo_ms:v7  #aca tal vez toca con usuario
    container_name: educativo
    
    ports:
    - "4000:4000"
    networks:
      - backend
  nginx:
    image: nginx:latest
    container_name: api_gateway
    ports:
      - "8080:80"    
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - seguimiento_postoperatorio
      - registro_usuario
    networks:
      - backend
networks:
  backend:
    driver: bridge
