services:
  seguimiento_postoperatorio:
    image: ymoras/seguimiento_postoperatorio_ms:latest
    container_name: seguimiento_postoperatorio
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb+srv://root:AAJJY52024-2@cluster0.ocbp0.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - MONGO_DATABASE=postcare_seguimiento_postoperatorio_db
      - SERVER_PORT=8081
      - SPRING_APPLICATION_NAME=seguimiento_postoperatorio_ms
    networks:
      - backend

  registro_usuario:
    image: amoralesco/postcare_registro_usuario_ms:v2
    container_name: registro_usuario
    ports:
      - "8000:8000" 
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: api_gateway
    ports:
      - "8080:80"    # Exposición del puerto HTTP (80) como 8080 en el host
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
      # - ./etc/nginx/api_conf.d:/etc/nginx/api_conf.d:ro
      # - ./etc/nginx/api_gateway.conf:/etc/nginx/api_gateway.conf:ro
      # - ./etc/nginx/api_json_errors.conf:/etc/nginx/api_json_errors.conf:ro
      # - ./etc/nginx/api_keys.conf:/etc/nginx/api_keys.conf:ro
      # - ./certs/postcareun.io.crt:/etc/ssl/certs/postcareun.io.crt:ro
      # - ./certs/postcareun.io.key:/etc/ssl/certs/postcareun.io.key:ro
    depends_on:
      - seguimiento_postoperatorio
      - registro_usuario
      - postcare_fe
    networks:
      - backend

  postcare_fe:
    image: jeramirezca/postcare_fe:v2
    container_name: postcare_fe
    ports:
      - "3000:3000" 
    networks:
      - backend

networks:
  backend:
    driver: bridge
