# Servicios backend para la API Warehouse
upstream warehouse_inventory {
    server 10.0.0.1:80;
    server 10.0.0.2:80;
}

upstream warehouse_pricing {
    server 10.0.0.3:80;
    server 10.0.0.4:80;
}
