error_page 400 = @400_json;
error_page 401 = @401_json;
error_page 403 = @403_json;
error_page 404 = @404_json;

location @400_json {
    return 400 '{"status":400,"message":"Bad request"}';
}

location @401_json {
    return 401 '{"status":401,"message":"Unauthorized"}';
}

location @403_json {
    return 403 '{"status":403,"message":"Forbidden"}';
}

location @404_json {
    return 404 '{"status":404,"message":"Resource not found"}';
}
